### ISSUE TITLE
Any future?

### ISSUE THREAD

**Issue by dumblob** [robotlolita/tamago#9]
I find this prototype quite cool - supporting the "imperative syntax" made up from a "functional syntax with holes" is really something more than just https://gist.github.com/gatlin/9696088 .

For teaching this sounds quite good to me (especially because it runs in a browser, so in ideal case no setup required). Maybe even for some demoing etc.

**Comment by robotlolita** [comment]
Not really in this form; there are a few ideas that did not work very well in the end for the things I had in mind, particularly stuff that added too many dynamic semantics or required too much intentional design for reuse.

Crochet (https://github.com/qteatime/crochet) is the spiritual successor, which keeps many of the same features, but embraces subtyping and multi-methods instead.

**Comment by dumblob** [comment]
Ok, thanks for the pointer to Crochet. Will take look.
